### PR TITLE
Fix double-question-mark output by builder.query.

### PR DESCRIPTION
**Pull request by rdefulio**
Resolves this error - "Sorry, the company context for this request is missing"

### CODE REVIEW

**Comment by ctolkien** [comment]
Hi @rdefulio  - sorry this PR got completely missed from my notifications. What bug is it actually addressing?

**Comment by rdefulio** [comment]
The extra question mark was causing the following error to be returned by
the clubhouse.io webapi - "Sorry, the company context for this request is
missing" even though it was included.

**Comment by bernatfortet** [comment]
Sounds like this issue is still active? @ctolkien @rdefulio

**Comment by ctolkien** [comment]
Ah, I see what this fixes now. Merging

Thanks!

**Comment by bernatfortet** [comment]
@ctolkien is this live right now?

**Comment by ctolkien** [comment]
Hi @bernatfortet  - not yet, sadly both my Nuget and GitHub API Keys used in the build steps have since expired (as it's been 2 years since working on this) so I need to update those as well before I can get a new build out.

**Comment by ctolkien** [comment]
Hi @bernatfortet  - I've manually uploaded a 2.0.1-beta release:
https://www.nuget.org/packages/ClubHouse/2.0.1-beta

Please give it a go and let me know if it solves your issues. In the interim, I'll get the CI bits fixed up again.

**Comment by bernatfortet** [comment]
Thanks!

**Pull request merged**
